services:
  postgres:
    build: ./postgres
    image: postgres:15.3-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DATASOURCE_URL}
      - POSTGRES_USER=${DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${DATASOURCE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M

volumes:
  postgres_data:
